bookmark/bookmarks/urls.py
from django.urls import path
from bookmarks import views

app_name = 'bookmarks'

urlpatterns  = [  
  # path('', views.bookmark_list, name='list'),
  # path('<int:pk>/', views.bookmark_detail, name='detail'),
  # path('create/', views.bookmark_create, name='create'),
  # path('update/<int:pk>/', views.bookmark_update, name='update'),
  # path('delete/<int:pk>/', views.bookmark_delete, name='delete')

  path('new/',views.BookmarkListView.as_view(), name='list'),
  path('new/<int:pk>/',views.BookmarkDetailView.as_view(), name='detail'),
  path('new/create/',views.BookmarkCreateView.as_view(), name='create'),
  path('new/update/<int:pk>/',views.BookmarkUpdateView.as_view(), name='update'),
  path('new/delete/<int:pk>/',views.BookmarkDeleteView.as_view(), name='delete')

]

bookmark/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from bookmarks import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('bookmark/', include('bookmarks.urls'))


    # path('bookmark/', views.bookmark_list),
    # path('bookmark/<int:pk>/', views.bookmark_detail),
    # path('bookmark/create/', views.bookmark_create),
    # path('bookmark/update/<int:pk>/', views.bookmark_update),
    # path('bookmark/delete/<int:pk>/', views.bookmark_delete)


]

bookmark/bookmarks/views.py
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponse
# Create your views here.
def index(request):
    return HttpResponse("<h1>hello world!</h1>")


from bookmarks.models import Bookmark
def bookmark_list(request):
    bookmark_list = Bookmark.objects.all()
    context = {'bookmark_list':bookmark_list}
    return render(request, 'bookmark_list.html', context)

from django.shortcuts import get_object_or_404
def bookmark_detail(request,pk):
    #bookmark = Bookmark.objects.get(id=pk)
    bookmark = get_object_or_404(Bookmark, id=pk)
    context = {'bookmark':bookmark}
    return render(request, 'bookmark_detail.html', context)

from .forms import BookmarkForm
def bookmark_create(request):
    #     context = {'text':'POST METHOD!!!'}
    #     return render(request, 'templates/bookmark_create.html',context)
    # context={'text':'GET METHOD'}
    # return render(request, 'templates/bookmark_create.html', context)
    # bookmark = Bookmark()
    # if request.method=='POST':
    #     bookmark.title = request.POST['title']
    #     bookmark.url = request.POST['url']
    #     bookmark.memo = request.POST['memo']

    #     bookmark.save()

    #     return redirect(f'/bookmark/{bookmark.id}/')

    # return render(request, 'bookmark_create.html')
    context = {}


    if request.method == "POST":
        form = BookmarkForm(request.POST)
        if form.is_valid():
            bookmark = form.save()
            return redirect(f'bookmarks:detail', bookmark.id)
    else:
        form = BookmarkForm()
        context['form'] = form
    return render(request, 'bookmark_create.html', context)




def bookmark_update(request, pk):
    bookmark = Bookmark.objects.get(id=pk)
    # context={'bookmark':bookmark}
    # if request.method=='POST':
    #     bookmark.title = request.POST['title']
    #     bookmark.url = request.POST['url']
    #     bookmark.memo = request.POST['memo']

    #     bookmark.save()

    #     return redirect(f'/bookmark/{bookmark.id}/')

    # return render(request, 'bookmark_update.html', context)
    context = {}


    if request.method == "POST":
        form = BookmarkForm(request.POST, instance = bookmark)
        if form.is_valid():
            bookmark = form.save()
            return redirect(f'bookmarks:detail', bookmark.id)
    else:
        form = BookmarkForm(instance=bookmark)
        context['form'] = form
    return render(request, 'bookmark_update.html', context)   


def bookmark_delete(request, pk):
    bookmark = Bookmark.objects.get(id=pk)
    context = {'haha':bookmark}

    if request.method == 'POST':
        bookmark.delete()
        return redirect('/bookmark/')

    return render(request, 'bookmark_delete.html', context)

from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView

class BookmarkListView(ListView):
    #1.모델 정하기
    model = Bookmark

    #2. context(변수명) 정하기
    context_object_name = 'bookmark_list'

    #어떤 templates연결한건지 정하기
    template_name = 'bookmark_list.html'

class BookmarkDetailView(DetailView):
    model=Bookmark
    context_object_name = 'bookmark'
    template_name = 'bookmark_detail.html'

from django.urls import reverse_lazy

class BookmarkCreateView(CreateView):
    model=Bookmark
    template_name = 'bookmark_create.html'
    form_class = BookmarkForm
    success_url = reverse_lazy('bookmarks:list')


class BookmarkUpdateView(UpdateView):
    model=Bookmark
    template_name = 'bookmark_Update.html'
    form_class = BookmarkForm
    success_url = reverse_lazy('bookmarks:list')

class BookmarkDeleteView(DeleteView):
    model=Bookmark
    template_name = 'bookmark_delete.html'
    success_url = reverse_lazy('bookmarks:list')
    context_object_name='bookmark'

bookmark/templates/bookmark_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


    <h1>북마크 등록하기</h1>

    <form method="post">
        {% csrf_token %}
        <!-- <input type="text" name="title" placeholder="북마크 제목">
        <input type="text" name="url" placeholder="북마크 url">
        <input type="text" name="memo" placeholder="북마크 메모"> -->
        {{ form.as_p }}

        <input type="submit" value="북마크 등록">


    </form>

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="포스트 요청 보내기">
    </form>

    {{ text }}


</body>
</html>

bookmark/templates/bookmark_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>북마크 삭제</h1>
    <form method="POST">
     {% csrf_token %}
     <p>북마크를 삭제하시겠습니까?</p>

     <input type="submit" value="네!">
     
    </form>
    <a href="{% url 'bookmarks:detail' bookmark.id %}">아니요!</a>
</body>
</html>

bookmark/templates/bookmark_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ bookmark.title }}</h1>
    <ul>
        <li>URL : <a href="bookmark.url"> {{ bookmark.url }}</a></li>
        <li>memo : {{ bookmark.memo }}</li>

</ul>
<a href="/bookmark/update/{{bookmark.id}}/">수정하기</a>
<a href="{% url 'bookmarks:update' bookmark.id %}">수정하기2</a>

<a href="/bookmark/delete/{{bookmark.id}}/">삭제하기</a>
<a href="{% url 'bookmarks:delete' bookmark.id %}">삭제하기2</a>


</body>
</html>

bookmark/templates/bookmark_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>북마크 리스트</h1>
    <ul>
        {% if bookmark_list %}
        {%for i in bookmark_list%}
          <li><a href="{% url 'bookmarks:detail' i.id %}">{{ i.title }}</a></li>
        {% endfor %}
    {% else %}
    <p>북마크가 없습니다!</p>
    {% endif %}
    </ul>
  <a href="{% url 'bookmarks:create' %}">북마크 등록하기</a>
</body>
</html>