mydjango/blogapp/urls.py
from django.urls import path
from blogapp import views

app_name='blogapp'
urlpatterns=[
    path('',views.PostListView.as_view(), name='list'),
    path('<int:pk>/',views.PostDetailView.as_view(), name='detail')
]

mydjango/bookmarkapp/urls.py
from django.urls import path
from bookmarkapp import views

app_name = 'bookmarkapp'

urlpatterns  = [  
  # path('', views.bookmark_list, name='list'),
  # path('<int:pk>/', views.bookmark_detail, name='detail'),
  # path('create/', views.bookmark_create, name='create'),
  # path('update/<int:pk>/', views.bookmark_update, name='update'),
  # path('delete/<int:pk>/', views.bookmark_delete, name='delete')

  path('new/',views.BookmarkListView.as_view(), name='list'),
  path('new/<int:pk>/',views.BookmarkDetailView.as_view(), name='detail'),
  path('new/create/',views.BookmarkCreateView.as_view(), name='create'),
  path('new/update/<int:pk>/',views.BookmarkUpdateView.as_view(), name='update'),
  path('new/delete/<int:pk>/',views.BookmarkDeleteView.as_view(), name='delete')

]

mydjango/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from mysite import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmarkapp.urls')),
    path('blog/' , include('blogapp.urls')),
    path('',views.HomeView.as_view()),
    path('about/',views.AboutView.as_view())
]

mydjango/blogapp/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name='글제목', max_length=20)
    context = models.TextField(verbose_name='글 내용')

    created_at = models.DateTimeField(verbose_name='생성시간', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='수정시간', auto_now=True)

mydjango/bookmarkapp/models.py
from django.db import models

# Create your models here.
class Bookmark(models.Model):
  title = models.CharField(verbose_name='북마크 이름', max_length=20, unique=True)
  url = models.URLField(verbose_name='URL')
  memo = models.TextField(verbose_name='메모')

mydjango/bookmarkapp/forms.py
from django import forms
from .models import Bookmark

class BookmarkForm(forms.ModelForm):
    class Meta:
        model = Bookmark
        fields = ['title', 'url', 'memo']
        #field = '_all_/'

mydjango/blogapp/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView,DetailView
from .models import Post

class PostListView(ListView):
    #1.모델 지정하기
    model = Post
    #2.변수명 지정
    context_object_name= 'posts'
    #3.templates 지정
    # template_name='blog_list.html'

class PostDetailView(DetailView):
    model=Post
    context_object_name='post'
    
    

mydjango/bookmarkapp/views.py
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponse
# Create your views here.
def index(request):
    return HttpResponse("<h1>hello world!</h1>")


from bookmarkapp.models import Bookmark
def bookmark_list(request):
    bookmark_list = Bookmark.objects.all()
    context = {'bookmark_list':bookmark_list}
    return render(request, 'bookmark_list.html', context)

from django.shortcuts import get_object_or_404
def bookmark_detail(request,pk):
    #bookmark = Bookmark.objects.get(id=pk)
    bookmark = get_object_or_404(Bookmark, id=pk)
    context = {'bookmark':bookmark}
    return render(request, 'bookmark_detail.html', context)

from .forms import BookmarkForm
def bookmark_create(request):
    #     context = {'text':'POST METHOD!!!'}
    #     return render(request, 'templates/bookmark_create.html',context)
    # context={'text':'GET METHOD'}
    # return render(request, 'templates/bookmark_create.html', context)
    # bookmark = Bookmark()
    # if request.method=='POST':
    #     bookmark.title = request.POST['title']
    #     bookmark.url = request.POST['url']
    #     bookmark.memo = request.POST['memo']

    #     bookmark.save()

    #     return redirect(f'/bookmark/{bookmark.id}/')

    # return render(request, 'bookmark_create.html')
    context = {}


    if request.method == "POST":
        form = BookmarkForm(request.POST)
        if form.is_valid():
            bookmark = form.save()
            return redirect(f'bookmarkapp:detail', bookmark.id)
    else:
        form = BookmarkForm()
        context['form'] = form
    return render(request, 'bookmark_create.html', context)




def bookmark_update(request, pk):
    bookmark = Bookmark.objects.get(id=pk)
    # context={'bookmark':bookmark}
    # if request.method=='POST':
    #     bookmark.title = request.POST['title']
    #     bookmark.url = request.POST['url']
    #     bookmark.memo = request.POST['memo']

    #     bookmark.save()

    #     return redirect(f'/bookmark/{bookmark.id}/')

    # return render(request, 'bookmark_update.html', context)
    context = {}


    if request.method == "POST":
        form = BookmarkForm(request.POST, instance = bookmark)
        if form.is_valid():
            bookmark = form.save()
            return redirect(f'bookmarkapp:detail', bookmark.id)
    else:
        form = BookmarkForm(instance=bookmark)
        context['form'] = form
    return render(request, 'bookmark_update.html', context)   


def bookmark_delete(request, pk):
    bookmark = Bookmark.objects.get(id=pk)
    context = {'haha':bookmark}

    if request.method == 'POST':
        bookmark.delete()
        return redirect('/bookmark/')

    return render(request, 'bookmark_delete.html', context)

from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView

class BookmarkListView(ListView):
    #1.모델 정하기
    model = Bookmark

    #2. context(변수명) 정하기
    context_object_name = 'bookmark_list'

    #어떤 templates연결한건지 정하기
   # template_name = 'bookmark_list.html'

class BookmarkDetailView(DetailView):
    model=Bookmark
    context_object_name = 'bookmark'
    #template_name = 'bookmark_detail.html'

from django.urls import reverse_lazy

class BookmarkCreateView(CreateView):
    model=Bookmark
    # template_name = 'bookmark_create.html'
    form_class = BookmarkForm
    success_url = reverse_lazy('bookmarkapp:list')


class BookmarkUpdateView(UpdateView):
    model=Bookmark
    #template_name = 'bookmark_Update.html'
    form_class = BookmarkForm
    success_url = reverse_lazy('bookmarkapp:list')
    context_object_name = 'bookmark'

class BookmarkDeleteView(DeleteView):
    model=Bookmark
  #  template_name = 'bookmark_delete.html'
    success_url = reverse_lazy('bookmarkapp:list')
    context_object_name='bookmark'

mydjango/mysite/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name='home.html'
class AboutView(TemplateView):
    template_name='about.html'

mydjango/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">만든 사람 : 고윤혁</h1>

<p class="text-center">이용한 기술 - Django,Bootsrtap</p>
<p class="text-center">코드 : <a href="https://github.com/OhyunIt2022/kohyounhyuk">코드</a></p>
<p class="text-center">깃헙 페이지 : <a href="https://github.com/kyh018">@kyh</a></p>


{% endblock %}

mydjango/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</head>
<body>
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>
  
        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
          <li><a href="/" class="nav-link px-2 link-secondary">Home</a></li>
          <li><a href="{% url 'bookmarkapp:list' %}" class="nav-link px-2 link-dark">Bookmark</a></li>
          <li><a href="{% url 'blogapp:list' %}" class="nav-link px-2 link-dark">Blog</a></li>
          <li><a href="/about/" class="nav-link px-2 link-dark">About</a></li>
        </ul>
  
        <div class="col-md-3 text-end">
          <button type="button" class="btn btn-outline-primary me-2">Login</button>
          <button type="button" class="btn btn-primary">Sign-up</button>
        </div>
      </header>
    <div class="container">
        <div class="row">
            <div class="col">

                {% block content %}{% endblock %}

            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
</body>
</html>

mydjango/templates/blogapp/post_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ post.title }}</h1>
    <p>{{ post.context }}</p>
    <p>작성시간 : {{ post.created_at }}}</p>
    <p>수정시간 : {{ post.updated_at }}}</p>
{% endblock %}

mydjango/templates/blogapp/post_list.html
{% extends 'base.html' %}

{% block content %}

<h1>Blog</h1>
    {% if posts %}
     <ul>
      {% for i in posts %}
           <li><a href="{% url 'blogapp:detail' i.id %}"> {{ i.title }} </a></li>
      {% endfor %}
     </ul>
    {% else %}
     <p> 포스트가 없습니다!</p>
    {% endif %}
{% endblock %}

mydjango/templates/bookmarkapp/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <p>북마크를 삭제하시겠습니까?</p>

    <input type="submit" value="네!">
    
   </form>
   <a href="{% url 'bookmarkapp:detail' bookmark.id %}">아니요!</a>
{% endblock %}

mydjango/templates/bookmarkapp/bookmark_detail.html
{% extends 'base.html' %}

{% block content %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Document</title>
</head>
<body>
<h1>{{ bookmark.title }}</h1>
<ul>
    <li>URL : <a href="bookmark.url"> {{ bookmark.url }}</a></li>
    <li>memo : {{ bookmark.memo }}</li>

</ul>
<a href="{% url 'bookmarkapp:update' bookmark.id %}">수정하기</a>

<a href="{% url 'bookmarkapp:delete' bookmark.id %}">삭제하기</a>
{% endblock %}

mydjango/templates/bookmarkapp/bookmark_form.html
{% extends 'base.html' %}

{% block content %}

{% if bookmark %}
    <h1>북마크 수정하기
    </h1>
    {% else %}


    <h1>북마크 등록하기</h1>
{% endif %}
    <form method="post">
        {% csrf_token %}
        <!-- <input type="text" name="title" placeholder="북마크 제목">
        <input type="text" name="url" placeholder="북마크 url">
        <input type="text" name="memo" placeholder="북마크 메모"> -->
        {{ form.as_p }}

        <input type="submit" value="북마크 등록">


    </form>

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="포스트 요청 보내기">
    </form>

    {{ text }}
 {% endblock %}

mydjango/templates/bookmarkapp/bookmark_list.html
{% extends 'base.html' %}

{% block content %}

<h1>북마크 리스트</h1>
<ul>
  {% if bookmark_list %}
     {%for i in bookmark_list%}
        <!-- 1. href 코등 수정하기 : 여기는 디테일 페이진로 연결 -->
          <li><a href="{% url 'bookmarkapp:detail' i.id %}">{{ i.title }}</a></li>
        {% endfor %}
    {% else %}
    <p>북마크가 없습니다!</p>
    {% endif %}
</ul>
    <!-- 2. 북마크 만들기 a태그 만들고, 연결 해주기 -->
  <a href="{% url 'bookmarkapp:create' %}">북마크 만들기 페이지</a>
{% endblock %}

mydjango/templates/bookmarkapp/bookmark_update.html
{% extends 'base.html' %}

{% block content %}

<h1>북마크 수정하기</h1>

    <form method="post">
        {% csrf_token %}
        <!-- <input type="text" name="title" placeholder="북마크 제목" value="{{bookmark.title}}">
        <input type="text" name="url" placeholder="북마크 url" value="{{bookmark.url}}">
        <input type="text" name="memo" placeholder="북마크 메모" value="{{bookmark.memo}}"> -->
        {{ form.as_p }}

        <input type="submit" value="북마크 수정">


    </form>
{% endblock %}

mydjango/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">내 장고 프로젝트의 첫 페이지입니다.</h1>
{% endblock %}